os: linux
dist: focal

language: node_js
node_js:
  - '16'

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - fakeroot
            - google-chrome-stable

cache:
    directories:
        - ./node_modules

install:
    - npm install

script:
    - cp src/environments/config.sample.ts src/environments/config.ts
    - npm run lint
    - npm run test:ci
    - npm run package
