#!/usr/bin/env python3
import os
import time
from http.server import HTTPServer, SimpleHTTPRequestHandler

from data_provider import NSDepartureTimesProvider

HTML_PAGE = '''<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="refresh" content="30">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/main.css" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 db-date">{date}</div>
                <div class="col-sm-6 db-time">{time}</div>
            </div>
            <div class="row">
                <div class="col-sm-6 data-block">
                    <h1>Houten Castellum</h1>
                    {houtenc}
                </div>
                <div class="col-sm-6 data-block">
                    <h1>Utrecht</h1>
                    {utrecht}
                </div>
            </div>
        </div>
    </body>
</html>
'''


# HTTPRequestHandler class
class HomePiRequestHandler(SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path != '/':
            return SimpleHTTPRequestHandler.do_GET(self)

        # Send response status code
        self.send_response(200)

        # Send headers
        self.send_header('Content-type', 'text/html')
        self.end_headers()

        # Fetch the data
        times_houtenc = NSDepartureTimesProvider('htnc').fetch()
        times_utrecht = NSDepartureTimesProvider('ut').fetch()

        args = {
            'date':    time.strftime('%A %d.%m'),
            'time':    time.strftime('%H:%M'),
            'houtenc': times_houtenc,
            'utrecht': times_utrecht,
        }

        # Write the response
        self.wfile.write(bytes(HTML_PAGE.format(**args), 'utf8'))


def run():
    dir_name = os.path.dirname(os.path.abspath(__file__))

    print('Server directory: ' + dir_name)
    os.chdir(dir_name)

    print('Starting server...')

    # Server settings
    # Choose port 8080, for port 80, which is normally used for a http server, you need root access
    server_address = ('', 8000)
    httpd = HTTPServer(server_address, HomePiRequestHandler)
    print('Running server...')
    httpd.serve_forever()


run()
