#!/usr/bin/env python3
import os
import logging

from backend.server import InfoPiServer

if __name__ == "__main__":
    dir_root = os.path.dirname(os.path.abspath(__file__))
    dir_web  = os.path.join(dir_root, 'web')

    # Setup logging
    logging.basicConfig(
        filename=os.path.join(dir_root, 'infopi.log'),
        level=logging.DEBUG,
        format='%(asctime)s  %(levelname)s %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S')

    # Navigate to the root dir of the project
    logging.info('========================================')
    logging.info('Web server directory: ' + dir_web)
    os.chdir(dir_web)

    # Instantiate and run the server
    logging.info('Starting web server...')
    InfoPiServer().run()
